### PR TITLE
feat(add-reminder-for-ocean-fishing): add a new reminder for ocean fishing every two hours

### PR DESCRIPTION
**Pull request by Jengines**
You can now enable a reminder for ocean fishing on reminders page

### CODE REVIEW

**Comment by Jengines** [comment]
I also fixed a bug for `realtime-alarm-service.ts#getTimeBefore` who got an incorrect time when the UTC hours for the alarm is the same as the current utc hour.

Related PR for added feature is: #2276

**Comment by Supamiu** [comment]
It looks like you added the translations in the JSON directly, this caused a conflict that you'll have to resolve 😄 shouldn't be too bad anyways.

**Comment by Jengines** [comment]
> It looks like you added the translations in the JSON directly, this caused a conflict that you'll have to resolve 😄 shouldn't be too bad anyways.

Should I have added the translation keys from another way?

**Comment by Jengines** [comment]
Conflicts resolved

**Comment by Supamiu** [comment]
> > It looks like you added the translations in the JSON directly, this caused a conflict that you'll have to resolve 😄 shouldn't be too bad anyways.
> 
> Should I have added the translation keys from another way?

Just add them to the en.json file and let crowdin catch them once it's merged, then translate on crowdin and it's done 👍

**Review by Supamiu — APPROVED** [review]

**Pull request merged**
